### PR TITLE
Move Spec Readme to the IBC repo

### PR DESCRIPTION
**Pull request by boojamya**
This PR moves the Spec Readme from this `IBC-GO` repo to the `IBC` repo here:
https://github.com/strangelove-ventures/ibc/pull/2

(Keeping all of this contained on a Strangelove fork).

This will align the docs with the other IBC apps. 

It also renames the folder: `modules/apps/icq` to `modules/apps/32-icq`

(I went ahead and selected "32" as the spec number)

### CODE REVIEW

**Review by alizahidraja — APPROVED** [review]
Added links to the ibc repo

**Comment by boojamya** [comment]
Ok, Nice.
@alizahidraja 
So, I actually did not add those links because I assumed that ICS-31 spec was for the quicksilver implementation. I assumed that the IBC team would assign a new ICS number for this version of the spec.

So will this implementation be ICS-31?

**Comment by Ehsan-saradar** [comment]
@alizahidraja 
Actually, our approach is not similar to ICS 031 (https://github.com/cosmos/ibc/blob/main/spec/app/ics-031-crosschain-queries/README.md), the quicksilver approach was based on  ICS 031

**Comment by alizahidraja** [comment]
Will we have two different specs for "interchain queries" & "cross-chain queries"?

**Comment by jackzampolin** [comment]
Yes we will. Talking to the informal and IG teams about this this week

**Comment by alizahidraja** [comment]
That's great!

I do have a small concern, shouldn't there be a single standard for queries rather than different specs for the same goal?

**Comment by boojamya** [comment]
Closing in favor of: https://github.com/strangelove-ventures/ibc-go/pull/12

**Pull request closed without merging**
