### PR TITLE
chore: relocating files to follow sdk module folder structure

### PR DESCRIPTION
**Pull request by crodriguezvega**
## Description

This PR is mostly re-locating files to into a regular SDK module folder structure.

Besides that, I have also included some changes to start removing the 08-wasm dependency from core IBC and complete the conversion of 08-wasm into an SDK module:

- The gRPC query `WasmCode` and the command `PushNewWasmCode` have been moved to 08-wasm's new gRPC query and message server. I have made these gRPC endpoints the only entry point for querying by code ID and storing new wasm code.
- The CLI query and command have also been moved out of core IBC's CLI.

In later PRs I will finish implementing the `AppModule` interface for 08-wasm and remove the wasm keeper from core IBC keeper.

closes: #XXXX

### Commit Message / Changelog Entry

```bash
type: commit message
```

see the [guidelines](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) for commit messages. (view raw markdown for examples)

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#pr-targeting)).
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/main/docs/docs/building-modules/10-structure.md) and [Go style guide](../docs/dev/go-style-guide.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/ibc-go/blob/master/CONTRIBUTING.md#testing).
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`).
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Provide a [commit message](https://github.com/cosmos/ibc-go/blob/main/CONTRIBUTING.md#commit-messages) to be used for the changelog entry in the PR description for review.
- [ ] Re-reviewed `Files changed` in the Github PR explorer.
- [ ] Review `Codecov Report` in the comment section below once CI passes.

### CODE REVIEW

**Comment by faddat** [comment]
Thank you

**Comment by crodriguezvega** [comment]
Hi @faddat. Thanks for your comment.

> Hey Carlos, does this mean that we won't merge 08-wasm into ibc-go?

No, the plan is still to upstream this module to ibc-go. :) We just  would like to do some work on Strangelove's fork first before we open a PR to ibc-go. We had a productive walkthrough of the code base a few weeks ago and some feedback points were identified, so I am trying to work on those (and any other that might come up in the meantime).

I hope this eases your concerns!

**Comment by faddat** [comment]
Actually it does.

I think it may make a lot of sense to get ICQ merged as well, but I'm glad that the plan is to upstream this. Thanks for your reply.

**Comment by misko9** [comment]
Hey Carlos, thanks for the PR and sorry about the delay. I finally got a chance to run it through our e2e testing. I think since this module is still an AppModuleBasic, the AppModule's RegisterServices() is not being call. So I'm getting the below error and we probably need to wait for the full transition to AppModule before merging in.

```
Received unexpected error:
        	            	failed to submit wasm client proposal: exit code 1:  Error: rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 0: /ibc.lightclients.wasm.v1.MsgPushNewWasmCode: proposal message not recognized by router [cosmos/cosmos-sdk@v0.47.0-rc1/x/gov/keeper/proposal.go:59] 
```

**Comment by misko9** [comment]
Throwing the wasm light client module into simd's module manager works. It's a temporary fix in its current state, but if this first release will have separation from core IBC, we can get this PR in now.

**Comment by crodriguezvega** [comment]
@misko9 Thanks for reviewing and merging the PR! I have a [follow-up PR](https://github.com/strangelove-ventures/ibc-go/pull/21) now that should complete the transition of 08-wasm into an SDK module. Please take a look when you have time!

**Pull request merged**
